enum AdvancedPhase {
    NONE,
    OPENING_1_BLACK_CENTER,
    OPENING_2_WHITE_AROUND_CENTER,
    OPENING_3_BLACK_WITHIN_TWO,
    OPENING_4_WHITE_FOURTH,
    OPENING_5_BLACK_FIRST,
    OPENING_5_BLACK_SECOND,
    OPENING_5_WHITE_REMOVE,
    NORMAL
}
